#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QGraphicsItem>
#include "architechtes.h"  // Ensure this file exists and contains the Architecte class
#include <QMainWindow>
#include <QTableWidget>
#include <QtCharts/QChartView>  // Include the necessary Qt Charts header
#include <QtCharts/QPieSeries>
#include <QtCharts/QPieSlice>
#include <QtCharts/QBarSeries>
#include <QtCharts/QBarSet>
#include <QtCharts/QChart>

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);  // Explicit keyword added to prevent implicit conversions
    ~MainWindow();  // Destructor to clean up the UI and other resources

    // Slot functions for buttons and interactions
    void on_addEmployeeButton_clicked();
    void on_supprimerEmploye_clicked();
    void on_modifyEmployeeButton_clicked();


private:
    Ui::MainWindow *ui;  // UI pointer generated by Qt's UI designer
    Architecte emp;  // Architecte object to manage employee data and logic
    void on_tableWidget_itemClicked(QTableWidgetItem *item);
    void refreshTableWidget();
    void fillTableWidget();
    void displayGenderStatistics();  // Declare the function here
     Architecte architecte;
     void on_rechercherButton_clicked();

private slots:
    void on_comboBox_tri_3_currentIndexChanged(int index);
};

#endif // MAINWINDOW_H
