#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include "architechtes.h"  // Ensure this file exists and contains the Architecte class
#include <QMainWindow>
#include <QTableWidget>

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);  // Explicit keyword added to prevent implicit conversions
    ~MainWindow();  // Destructor to clean up the UI and other resources

    // Slot functions for buttons and interactions
    void on_addEmployeeButton_clicked();
    void on_supprimerEmploye_clicked();
    void on_modifyEmployeeButton_clicked();

private:
    Ui::MainWindow *ui;  // UI pointer generated by Qt's UI designer
    Architecte emp;  // Architecte object to manage employee data and logic
    void on_tableWidget_itemClicked(QTableWidgetItem *item);
    void refreshTableWidget();
    void fillTableWidget();  // Method to populate the QTableWidget with employee data
};

#endif // MAINWINDOW_H
